import { FSConfiguration } from "../src/api-generation/types";

// Constants and configuration for the API generation process
// members and types in Assembly-CSharp.dll with these attributes will be ignored
const IGNORE_ATTRIBUTES = {
  "System.Runtime.CompilerServices.CompilerGeneratedAttribute": true,
};

const placeholders = {
  typeDescription: "No description available.",
  memberDescription: "No description available.",
  namespaceDescription: "No description available.",
};

const frontmatter = {
  shortDescriptionAutogeneratedKey: "autogenerated_short_description", // boolean sidecar key
  longDescriptionAutogeneratedKey: "autogenerated_long_description", // boolean sidecar key
};

const configuration: FSConfiguration = {
  ignoreAttributes: IGNORE_ATTRIBUTES,
  globalNamespaceName: "Global",
  outputDir: "api/reference",
  shouldGenerateSidecars: true,
  sidecarsOutputDir: "api/sidecars",
  gameVersion: "",
  manifest: undefined,
};

export default {
  placeholders,
  configuration,
  frontmatter,
};
